export `setSpecialConfigValues` to window to allow to creation of
liqd/django-ckeditor-5 pull request #3
Opened 2023-12-04 13:35 UTC by goapunk

a CKEDITOR instance from js (e.g. used in the documents app)

2023-12-04 15:19 UTC, philli-m requested changes
don't think it will work with no cookie but can't test

2023-12-04 15:19 UTC, philli-m commented on django_ckeditor_5/static/django_ckeditor_5/app.js
> +                ],
will this work with youtube-nocookie urls? its what you get if you use the embed url and click the box 'enhaced privacy` checkbox

2023-12-04 15:20 UTC, philli-m commented on django_ckeditor_5/static/django_ckeditor_5/app.js
> +                ],
also should we wrap all options with maybe mobile check or is that not required for other urls?

2023-12-04 15:26 UTC, goapunk commented
> don't think it will work with no cookie but can't test

you can test on dev, it's the same logic

2023-12-04 15:28 UTC, goapunk commented on django_ckeditor_5/static/django_ckeditor_5/app.js
> +                ],
I copied this from ckeditor, I didn't look too closely. I think `youtou.be` just redirects to `youtube.com` so it should be ok

2023-12-04 15:29 UTC, goapunk commented on django_ckeditor_5/static/django_ckeditor_5/app.js
> +                ],
but yeah most likely won't work with youtube-nocookie

2023-12-05 07:37 UTC, goapunk commented on django_ckeditor_5/static/django_ckeditor_5/app.js
> +                ],
added a fix

2023-12-05 10:42 UTC, philli-m approved these changes
Nice videos work as does ckeditor in docs

2023-12-05 10:42 UTC, merged